// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrb09fS48ku7ECQXsUVp78FYOOLTXkgRA',
    appId: '1:992156619289:web:4c4971a7cbfe67a3c91088',
    messagingSenderId: '992156619289',
    projectId: 'test-mynotes-project-flutter',
    authDomain: 'test-mynotes-project-flutter.firebaseapp.com',
    storageBucket: 'test-mynotes-project-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDcN7zvlP-juTacIBorOtWlVCz6yj6AsI',
    appId: '1:992156619289:android:9874ee2a3130da82c91088',
    messagingSenderId: '992156619289',
    projectId: 'test-mynotes-project-flutter',
    storageBucket: 'test-mynotes-project-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD51fRNvqk4cEhjdZKnsQjbq7rjnoQTPIs',
    appId: '1:992156619289:ios:b0adc3fb37a4945dc91088',
    messagingSenderId: '992156619289',
    projectId: 'test-mynotes-project-flutter',
    storageBucket: 'test-mynotes-project-flutter.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD51fRNvqk4cEhjdZKnsQjbq7rjnoQTPIs',
    appId: '1:992156619289:ios:b0adc3fb37a4945dc91088',
    messagingSenderId: '992156619289',
    projectId: 'test-mynotes-project-flutter',
    storageBucket: 'test-mynotes-project-flutter.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrb09fS48ku7ECQXsUVp78FYOOLTXkgRA',
    appId: '1:992156619289:web:f0d5614530c5dc94c91088',
    messagingSenderId: '992156619289',
    projectId: 'test-mynotes-project-flutter',
    authDomain: 'test-mynotes-project-flutter.firebaseapp.com',
    storageBucket: 'test-mynotes-project-flutter.appspot.com',
  );
}
